### ISSUE TITLE
QEMU issues

### ISSUE THREAD

**Issue by japaric** [japaric/rustc-builtins#2]
### Update

Trying to run the test suite on QEMU for some targets crashes QEMU

- [ ] [`armv7-unknown-linux-gnueabihf`](https://travis-ci.org/japaric/rustc-builtins/jobs/150901313#L355)
- [x] [`mips-unknown-linux-gnu`](https://travis-ci.org/japaric/rustc-builtins/jobs/150901316#L658)
- [x] [`powerpc64-unknown-linux-gnu`](https://travis-ci.org/japaric/rustc-builtins/jobs/150901319#L682)
- [ ] [`powerpc64le-unknown-linux-gnu`](https://travis-ci.org/japaric/rustc-builtins/jobs/150901320#L684)

I'm not quite sure what's the exact problem for each target but some possible causes:

- The `std` binaries for the target are "broken". Most likely, some C binding in `libc` is wrong.
- We are using the wrong QEMU variant (`qemu-ppc64le`).
- "Just" a problem with multithreading. This leads to *sporadic* failures.

In some cases, using QEMU's system emulation instead of user emulation might fix the problem.

---

[Example](https://travis-ci.org/japaric/rustc-builtins/jobs/150516428#L337).

Emphasis on **sometimes**. This is weird because (a) as of e5ab308115e7e581d5579126f74eba9ad249cb4b, the test suite is deterministic and (b) I'm using `RUST_TEST_THREADS=1` to "prevent" multithreading (QEMU is known to have problems handling multiple threads) but I guess this last part is impossible because detecting a panic requires at least two threads.

**Comment by Amanieu** [comment]
Yes, that looks like qemu-user is failing due to threads. There's not much you can do about it. One way to solve it would be to use qemu-system-arm instead and run the tests in a full VM (though you can probably get away with just the kernel and running the test with `init=/test`, in which case all you need is a kernel image).

**Comment by japaric** [comment]
@Amanieu Thanks for taking a peek.

> Yes, that looks like qemu-user is failing due to threads.

What I feared. :scream_cat: 

> One way to solve it would be to use qemu-system-arm instead and run the tests in a full VM

Sounds annoying. Know of any place where I can get an ARM kernel image? For the rootfs I think I can use one of ubuntu-core's.

> though you can probably get away with just the kernel and running the test with init=/test, in which case all you need is a kernel image

Hmm, I'm not sure. The test binary is dynamically linked and depends on libc and other C libraries.

**Comment by Amanieu** [comment]
[This](https://github.com/rust-lang/libc/tree/master/ci#qemu) might be helpful.

**Comment by japaric** [comment]
> mips-unknown-linux-gnu
> powerpc64-unknown-linux-gnu
> powerpc64le-unknown-linux-gnu

QEMU for these three targets appears to be [flat](https://travis-ci.org/japaric/smoke/jobs/151127978#L640) [out](https://travis-ci.org/japaric/smoke/jobs/151127981#L664) [broken](https://travis-ci.org/japaric/smoke/jobs/151127982#L666). Even this simple program causes a segfault when executed with QEMU for these targets:

``` c
int main() { return 0; }
```

This [issue](https://bugs.launchpad.net/qemu/+bug/1361912) have been reported upstream but there has been no action. Also, someone [claims](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=678029#67) that the 32-bit version of qemu-$TARGET doesn't segfault on amd64. Might try that.

**Comment by japaric** [comment]
> Also, someone claims that the 32-bit version of qemu-$TARGET doesn't segfault on amd64. Might try that.

And, weirdly enough, it actually works! At least on MIPS. Will send a PR.

**Comment by japaric** [comment]
> And, weirdly enough, it actually works! At least on MIPS. Will send a PR.

Fixed the mips and ppc64 targets. The trick didn't work on the ppc64le target.

**Comment by japaric** [comment]
Switching Travis to exclusively use Docker (Ubuntu 16.04) fixed the flakiness of the ARM targets. The ppc64le target still doesn't work (QEMU appears to be busted) but I'm OK with that; we got 16 of 17 targets working so I'm gonna close this.
