### ISSUE TITLE
Add the dumbest implementation of mem{cpy,move,set}

### ISSUE THREAD

**Issue by shepmaster** [japaric/rustc-builtins#28]
I have these (needed for the AVR work), would you like to add them in here for now?

I know we don't have the weak linking situation well-understood, so one (terrible?) possibility is that we could simply `include!('mem.rs')` in the architectures that need it.

**Comment by Amanieu** [comment]
I think the solution we decided on was to leave those to `rlibc`. So you would need to link to that crate in addition to `rustc-builtins`.

**Comment by japaric** [comment]
@shepmaster We actually tried to add them before (see #14 #15 #16) but there was a problem when using LTO to build an executable (`memcpy` got misoptimized to a recursive call). There problem has been reported upstream as rust-lang/rust#35540. Once that's fixed we'll add `memcpy` et al here as weak symbols.

In the meantime, as @Amanieu said, you can use the [rlibc](https://crates.io/crates/rlibc) crate. My understanding is that you should only need that crate when building an executable (or staticlib) and not for e.g. cross compiling an rlib like `core` to AVR, is that correct?

> needed for the AVR work

I was about to contact you about this :smile:. Do you have a list of the intrinsics that are needed to build AVR programs? I'd love to prioritize porting those to Rust.

**Comment by shepmaster** [comment]
> My understanding is that you should only need that crate when building an executable (or staticlib) and not for e.g. cross compiling an rlib like core to AVR, is that correct?

I am indeed attempting to compile into an executable.

I haven't even tried to actually cross-compile libcore in a usable way. I just have a Cargo.toml that points at a copy of the libcore code and I edit everything to have references to it (which is quite annoying). I should investigate getting that to be available...

> a list of the intrinsics that are needed to build AVR programs

Not a list, no. I've just run into one or two as I've tried to compile more things. Amusingly, compiler-rt doesn't even implement some of them! It actually expects to link against something from gcc, I suppose.

I have that one intrinsic in a local branch though, I'd be happy to send a PR for it.

**Comment by japaric** [comment]
> I've just run into one or two as I've tried to compile more things.

That would be the list I'm talking about :smile:. We are adding them as we find out we need them (at least for `no_std` targets).

> Amusingly, compiler-rt doesn't even implement some of them!

You mean in upstream compiler-rt? Our compiler-rt is pretty outdated I think. Perhaps upstream doesn't have them because the AVR fork hasn't been totally merged yet (or has it? I'm not following closely).

> I have that one intrinsic in a local branch though, I'd be happy to send a PR for it.

We'll be happy to take it (with tests)!
