### ISSUE TITLE
Upload CI disassembilies to Pastebin/Gist

### ISSUE THREAD

**Issue by mattico** [japaric/rustc-builtins#51]
The disassembly makes the CI logs really long, which makes the page load slowly, and could obscure errors which happen after them. This problem is only going to get worse as the library gets bigger. Uploading the disassembly to \<somewhere\> makes it fairly easy to have a disassembly available for every build, but makes the logs more manageable.

**Comment by japaric** [comment]
:+1: On Linux, at least, we can use something like the wgetpaste command.

**Comment by japaric** [comment]
Linux and Windows are now using gist. OSX is not using gist yet.
