### ISSUE TITLE
Integrate UB fix in floatsidf and floatsisf

### ISSUE THREAD

**Issue by japaric** [japaric/rustc-builtins#85]
cf. rust-lang/compiler-rt#24

These fixes are not in the llvm-mirror/compiler-rt repo which we are using.

**Comment by alexcrichton** [comment]
Ideally we'd upstream, but that may take a bit...

Agreed should use a fork in the meantime to speed things along.

**Comment by japaric** [comment]
So, we could just switch to the rust-lang/compiler-rt repo.

**Comment by alexcrichton** [comment]
👍
